"""add coupon review notification wishlist password_reset product_image product_relation tables

Revision ID: 1629e3fbf984
Revises: f76012034f61
Create Date: 2026-09-06 16:36:22.235912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1629e3fbf984'
down_revision = 'f76012034f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed_amount', name='discount_type'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discount_coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discount_coupons_code'), ['code'], unique=True)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('notification_type', sa.String(length=60), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND customer_id IS NULL) OR (user_id IS NULL AND customer_id IS NOT NULL)', name='ck_reset_token_one_of'),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('product_composition_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('content_name_ar', sa.String(length=200), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_composition_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_composition_lines_product_id'), ['product_id'], unique=False)

    op.create_table('product_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_features_product_id'), ['product_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('related_product_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('RELATED', 'FREQUENTLY_BOUGHT', name='relationtype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'related_product_id', 'relation_type', name='uq_product_relation')
    )
    with op.batch_alter_table('product_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_relations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relations_related_product_id'), ['related_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_relations_relation_type'), ['relation_type'], unique=False)

    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'customer_id', name='uq_product_review')
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_reviews_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reviews_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='uq_wishlist_item')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_product_id'), ['product_id'], unique=False)

    op.create_table('stock_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_alerts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_alerts_notified_at'), ['notified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_alerts_variant_id'), ['variant_id'], unique=False)

    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['discount_coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id', 'order_id', name='uq_coupon_order')
    )
    with op.batch_alter_table('coupon_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_usages_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_usages_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coupon_usages_order_id'), ['order_id'], unique=False)

    op.create_table('loyalty_points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('transaction_type', sa.Enum('earn', 'redeem', 'adjust', name='loyalty_txn_type'), nullable=False),
    sa.Column('reference_order_id', sa.Integer(), nullable=True),
    sa.Column('reference_invoice_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['parties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_invoice_id'], ['sales_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_points_ledger_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compare_at_price', sa.Numeric(precision=18, scale=3), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('origin_country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('piece_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=18, scale=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('piece_count')
        batch_op.drop_column('origin_country')
        batch_op.drop_column('offer_ends_at')

    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_column('compare_at_price')

    with op.batch_alter_table('loyalty_points_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_points_ledger_customer_id'))

    op.drop_table('loyalty_points_ledger')
    with op.batch_alter_table('coupon_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_usages_order_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_usages_customer_id'))
        batch_op.drop_index(batch_op.f('ix_coupon_usages_coupon_id'))

    op.drop_table('coupon_usages')
    with op.batch_alter_table('stock_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_alerts_variant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_alerts_notified_at'))
        batch_op.drop_index(batch_op.f('ix_stock_alerts_email'))
        batch_op.drop_index(batch_op.f('ix_stock_alerts_customer_id'))

    op.drop_table('stock_alerts')
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_items_customer_id'))

    op.drop_table('wishlist_items')
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_reviews_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_reviews_is_approved'))
        batch_op.drop_index(batch_op.f('ix_product_reviews_customer_id'))

    op.drop_table('product_reviews')
    with op.batch_alter_table('product_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_product_relations_related_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_relations_product_id'))

    op.drop_table('product_relations')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('product_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_features_product_id'))

    op.drop_table('product_features')
    with op.batch_alter_table('product_composition_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_composition_lines_product_id'))

    op.drop_table('product_composition_lines')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_customer_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('discount_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discount_coupons_code'))

    op.drop_table('discount_coupons')
    # ### end Alembic commands ###
